include(FetchContent)

include(cmake/dependencies/skia.cmake)
include(cmake/dependencies/atlasGenerator.cmake)
include(cmake/dependencies/CDT.cmake)
include(cmake/dependencies/SDK.cmake)
include(cmake/dependencies/spdlog.cmake)
include(cmake/dependencies/SupercellSWF.cmake)
include(cmake/dependencies/wxWidget.cmake)
include(cmake/dependencies/zip.cmake)