include(FetchContent)

include(cmake/atlasGenerator.cmake)
include(cmake/blend2d.cmake)
include(cmake/CDT.cmake)
include(cmake/SDK.cmake)
include(cmake/spdlog.cmake)
include(cmake/SupercellSWF.cmake)
include(cmake/wxWidget.cmake)
include(cmake/zip.cmake)